export const MatchType = {
  BOOKMAKER: "bookmaker",
  BOOKMAKER2: "bookmaker2",
  QUICKBOOKMAKER: "quickBookmaker",
  MATCH_ODDS: "matchOdds",
  SESSION_MARKET: "sessionMarket",
  API_SESSION_MARKET: "apiSessionMarket",
  API_TIED_MATCH2: "tiedMatch2",
  API_TIED_MATCH: "tiedMatch1",
  API_TIED_MATCH3: "tiedMatch3",
  CRICKET_CASINO_SESSION_MARKET: "cricketCasinoMarket",
  UNDER_OVER: "underOver",
  SET_WINNER: "setWinner",
  OTHER: "other",
  TOURNAMENT: "tournament",
  completeMatch: "completeMatch",
  completeMatch1: "completeMatch1",
  completeManual: "completeManual",
};
